#!/usr/bin/env bash
# Shebang is not needed as the script is not executed but sourced
# but we use it to get the IDE file type

# Non-Interactive environment

# Executed by:
# * IDE: `wsl git`
# * bash script with shebang

###########################################
# The scripts should set env or source env file only,
# not executing any bash script to avoid any recursion
# (ie a bash script executed will source this file)
###########################################

[[ "$-" == *i* ]] && return
echo ".bashenv called by ${0}" >/dev/stderr

##############################
# Load sub bash env script
##############################
if [ -d "$HOME/.bashenv.d" ]; then
  # All file loaded in a directory should have a sh extension
  # This is how /etc/profile also work
  for file in "$HOME"/.bashenv.d/*.sh; do
    # shellcheck disable=SC1090
    [ -r "$file" ] && source "$file"
  done
  unset file
fi

