#!/bin/bash

##########################################
# Standard/Library function
##########################################
# Some example functions:
#
# a) function settitle
# settitle ()
# {
#   echo -ne "\e]2;$@\a\e]1;$@\a";
# }
#



