#!/bin/bash

# ~/.profile: executed by the command interpreter for login shells.
# Note:
# Running wsl (bash.exe) without arguments (or with the ~ argument) will launch bash as a login shell.

# Executed when the terminal is starting (ie non-interactive)
# On Windows, the terminal is started with: `wsl.exe --distribution Debian`
#
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# .bashrc does not run by default on non-interactive session
# ie does not run when the terminal is started
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	    . "$HOME/.bashrc"
    fi
fi

