#!/bin/bash

# Login shell (ie start script)
# Executed when bash is starting (for a terminal or for each script)

# ~/.profile: executed by the command interpreter for login shells.
# Read by:
#   * shell script at start
#   * Idea Ide to set system env on Linux
#   * the terminal on startup
#   * wsl.exe --distribution Debian (from windows(

# Don't output to stdout as this file is called for each instantiation of bash

# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# bug??? Called twice by Idea ??? but not by wsl
# You can test it by adding a return after the echo

# Calling echo to check that it's not called a crazy number of times
calling_command=$(ps -o cmd= -p $PPID)
# pstree -p $PPID >/dev/stderr
echo "$HOME/.profile: Started by ${0} (Sourced by (${BASH_SOURCE[1]}), $# Args: $*) <- Parent (command: $calling_command, Id $PPID) " >/dev/stderr

# bug??? Called twice by Idea ??? but not by wsl
if [ "${DOT_PROFILE_CALLED}" != "" ]; then
  echo "$HOME/.profile already called (Idea bug)" >/dev/stderr
  # We can't return otherwise the bash functions are not loaded
fi
export DOT_PROFILE_CALLED="yes"

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

##############################
# Loading env variable
##############################
echo "$HOME/.profile: Loading env variables" >/dev/stderr
if [ -d "$HOME/.profile.d" ]; then
  # All file loaded in a directory should have a sh extension
  # This is how /etc/profile also work
  for file in "$HOME"/.profile.d/*.sh; do
    # shellcheck disable=SC1090
    [ -r "$file" ] && source "$file"
  done
  unset file
fi
echo "$HOME/.profile: Env variables loaded" >/dev/stderr
##############################
# Loading bash env script (alias, function, ...)
##############################
# .bashrc does not run by default on login shell
# ie does not run when the terminal is started
# If we are not running interactively, we return
if [[ "$-" != *i* ]]; then
  echo "$HOME/.profile: Session is non-interactive. No bashrc. Returning" >/dev/stderr
  return
fi
echo "Loading bash env (alias, function, ...) for interactive/repl session" >/dev/stderr
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	    . "$HOME/.bashrc"
    fi
fi


