#!/usr/bin/env bash
# Shebang is not needed as the script is not executed but sourced
# but we use it to get the IDE file type

# Environment in IDE
# Called only in non-interactive mode
# Should set only ENV
[[ "$-" == *i* ]] && return
echo ".bashenv called" >/dev/tty

# For SSH-X (ie loading of key in Intellij)
source "$HOME/.bashrc.d/ssh-x.sh"
source "$HOME/.bashrc.d/pass.sh"

