#!/usr/bin/env bash
# A pass wrapper to intercept who is calling pass

set -Eeuo pipefail
export PATH=${SSH_BASHLIB_LIBRARY_PATH}:$PATH

# Trying to see who call it
source "bashlib-stack.sh"
BASE_DIR="$HOME/code/nico/tmp/"
DAY_LOG_DIR="$BASE_DIR/$(date +"%Y-%m-%d")"
mkdir -p "$DAY_LOG_DIR"
stack::print_process_tree >> "$DAY_LOG_DIR/$(date +"%Y%m%d-%H%M%S")-pass.log"

# Run
# We select the second in path order
# Why? we may get it from the project (ie sdk man) and also globally from brew.
# We take the second in order of priority
/usr/bin/pass "$@"
