#!/usr/bin/env bash

# Aider Wrapper script to get the appropriate key
# by project

# Project name should be in a envrc
PROJECT_NAME=${PROJECT_NAME:-}
if [ "$PROJECT_NAME" == "" ]; then
  echo "Project Name env (PROJECT_NAME) is missing"
  return 1
fi
ORGANIZATION_NAME=${ORGANIZATION_NAME:-}
if [ "$ORGANIZATION_NAME" == "" ]; then
  echo "Organization Name env (ORGANIZATION_NAME) is missing"
  return 1
fi

# "$(which -a git | sed -n '2p')" "$@"
AIDER_PATH=${AIDER_PATH:-"$HOME/.venv/bin/aider"}
if ! [ -f "$AIDER_PATH" ]; then
  echo "Aider not found at $AIDER_PATH."
  echo "Possible Solutions: Set the AIDER_PATH env to another path"
  return 1
fi

case "${LLM:-}" in
"openai")
  ENV_NAME="OPENAI_API_KEY"
  PROJECT_NAME="${PROJECT_NAME}-project"
  PROVIDER="openai"
  ;;
"claude")
  ENV_NAME="ANTHROPIC_API_KEY"
  PROVIDER="anthropic"
  ;;
"openrouter")
  # 5% + .35 fee
  # use lite.llm
  ENV_NAME="OPENROUTER_API_KEY"
  PROVIDER="openrouter"
  ;;
*)
  echo "LLM ${LLM:-} is unknown"
  echo "Set LLM env to openai, claude or openrouter"
  return 1
  ;;
esac

LLM_KEY_PATH="${PROVIDER}/${ORGANIZATION_NAME}/${PROJECT_NAME}"
if ! LLM_KEY=$(pass "$LLM_KEY_PATH"); then
  echo "${LLM:-} Api Key Not Found at $LLM_KEY_PATH"
  LLM_KEY_PATH="${PROVIDER}/${ORGANIZATION_NAME}/default"
fi
if ! LLM_KEY=$(pass "$LLM_KEY_PATH"); then
  echo "${LLM:-} Api Key Not Found at $LLM_KEY_PATH"
  return 1
fi

eval "$ENV_NAME=$LLM_KEY $AIDER_PATH $*"
