# The default tarball-ttl in Nix is 1 hour.
# So if you start a shell less frequently than once per hour, Nix considers the cached tarball stale and re-checks (and re-unpacks) it.
# 7 days in seconds
tarball-ttl = 604800
