# https://direnv.net/man/direnv.toml.1.html

[global]
strict_env = true
warn_timeout = "1s"
load_dotenv = true # load .env files if envrc is not present

# Trusted directories
[whitelist]
prefix = [ "~/code" ]